
development:
  adapter: postgresql
  encoding: unicode
  database: property_manager_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: property_manager_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: property_manager_production
  pool: 5
  username:
  password:
